### PR TITLE
Add cable driver to E2E matrix

### PR DESCRIPTION
**Pull request by dfarrell07**
Run E2E tests with all cable drivers and with/without globalnet.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
It seems setting the cable driver isn't working. From the strongSwan job:

```
2020-12-10T10:05:55.6560859Z [36m[submariner-charts]$ [cluster2] subctl show connections[0m
2020-12-10T10:05:55.6577223Z [36m[submariner-charts]$ [cluster2] grep connected[0m
2020-12-10T10:05:55.8648458Z cluster2-worker                 cluster2                172.17.0.6      libreswan           100.2.0.0/16, 10.2.0.0/16               connected       
2020-12-10T10:05:55.8649563Z cluster1-worker                 cluster1                172.17.0.5      libreswan           100.1.0.0/16, 10.1.0.0/16               connected    
```

**Comment by nyechiel** [comment]
bump /cc @dfarrell07

**Comment by dfarrell07** [comment]
It's still not working, those are false-positives. Independently, I need to remove the Strongswan part now that it's fully deprecated.

```
2021-01-27T17:41:28.6901248Z [36m[submariner-charts]$ [cluster2] subctl show connections[0m
2021-01-27T17:41:28.6913514Z [36m[submariner-charts]$ [cluster2] grep connected[0m
2021-01-27T17:41:28.8822450Z cluster2-worker                 cluster2                172.17.0.6      libreswan           100.2.0.0/16, 10.2.0.0/16               connected  
```

From Wireguard job.

```
2021-01-27T17:40:22.6566352Z [36m[submariner-charts]$ [cluster2] subctl show connections[0m
2021-01-27T17:40:22.6580667Z [36m[submariner-charts]$ [cluster2] grep connected[0m
2021-01-27T17:40:23.7285591Z [36m[submariner-charts]$ [cluster2] return 0[0m
2021-01-27T17:40:23.7286749Z cluster2-worker                 cluster2                172.17.0.4      libreswan           100.2.0.0/16, 10.2.0.0/16               connected       
```

From Libreswan job.

**Comment by nyechiel** [comment]
@dfarrell07 what's the status of this one?

**Comment by dfarrell07** [comment]
> @dfarrell07 what's the status of this one?

@nyechiel It's still not actually changing the cable driver. It seems to be passed through the Shipyard GHA and using= flag to the Helm deploy correctly, but the actually-deployed cable driver doesn't change.

From the Wireguard job:

```
2021-03-03T16:31:14.2645827Z [36m[submariner-charts]$ [cluster2] subctl show connections[0m
2021-03-03T16:31:14.2664433Z [36m[submariner-charts]$ [cluster2] grep connected[0m
2021-03-03T16:31:14.3074843Z cluster2-worker                 cluster2                172.17.0.7      libreswan           100.2.0.0/16, 10.2.0.0/16               connected       
2021-03-03T16:31:14.3075931Z cluster1-worker                 cluster1                172.17.0.4      libreswan           100.1.0.0/16, 10.1.0.0/16               connected 
```

https://pastebin.com/DVip001R

**Comment by dfarrell07** [comment]
We need infra to run post mortem on successful jobs via a label on PRs (and always for periodic jobs), as discussed on an automation call. Without the post mortem there's not a lot to debug from.

**Comment by dfarrell07** [comment]
Okay it's correctly-passing now. Thanks for https://github.com/submariner-io/submariner-charts/pull/123 @SteveMattar!

```
2021-03-04T17:59:34.4693551Z [36m[submariner-charts]$ [cluster2] grep connected[0m
2021-03-04T17:59:34.5049577Z cluster1-worker                 cluster1                172.17.0.5      wireguard           100.1.0.0/16, 10.1.0.0/16               connected       
2021-03-04T17:59:34.5050706Z cluster2-worker                 cluster2                172.17.0.7      wireguard           100.2.0.0/16, 10.2.0.0/16               connected   
```

**Review by SteveMattar — APPROVED** [review]

**Review by tpantelis — APPROVED** [review]

**Pull request merged**
