### PR TITLE
Bump chart version to 0.15.0

### PR DESCRIPTION
**Pull request by tpantelis**

### CODE REVIEW

**Review by abguptms — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Comment by dfarrell07** [comment]
Various failures in required jobs, re-running.

**Comment by dfarrell07** [comment]
> Various failures in required jobs, re-running.

Weird, I can only re-run one of them (at a time?).

**Comment by dfarrell07** [comment]
All the GN jobs were failing, but I was able to re-run normally. Let's see if it happens again.

**Comment by tpantelis** [comment]
> All the GN jobs were failing, but I was able to re-run normally. Let's see if it happens again.

I fixed the issue with GN.

**Comment by tpantelis** [comment]
I need another approval.  @dfarrell07 @sridhargaddam

**Pull request merged**
