### PR TITLE
Remove questions.yml

### PR DESCRIPTION
**Pull request by tpantelis**
There's no mention in the upstream helm docs about this file nor is there any docs about interactive user prompting at all (that I can see). Nor do we document any mechanism for user prompting. It would seem this is an obsolete remnant from an earlier version of helm so let's remove it. This also eliminates hard-coded image versions that need to be updated.

### CODE REVIEW

**Review by dfarrell07 — APPROVED** [review]
Seems to be a Rancher feature: https://www.rancher.co.jp/docs/rancher/v2.x/en/catalog/custom/creating/#rancher-chart-additional-files

**Comment by tpantelis** [comment]
> Seems to be a Rancher feature: https://www.rancher.co.jp/docs/rancher/v2.x/en/catalog/custom/creating/#rancher-chart-additional-files

Interesting - thanks for finding this. Should we keep it then and maintain it....  It's effectively an untested feature.

**Comment by dfarrell07** [comment]
> > Seems to be a Rancher feature: https://www.rancher.co.jp/docs/rancher/v2.x/en/catalog/custom/creating/#rancher-chart-additional-files
> 
> Interesting - thanks for finding this. Should we keep it then and maintain it.... It's effectively an untested feature.

I don't think so, it's an optional UX help for code we can't test.

**Comment by tpantelis** [comment]
> > Interesting - thanks for finding this. Should we keep it then and maintain it.... It's effectively an untested feature.
> 
> I don't think so, it's an optional UX help for code we can't test.

I suppose we could test it if we know how 😄 But it would be manual. I'm inclined to remove it - @skitt ?

**Review by skitt — APPROVED** [review]

**Comment by skitt** [comment]
> I suppose we could test it if we know how smile But it would be manual. I'm inclined to remove it - @skitt ?

Yes, let’s remove it.

**Pull request merged**
