### PR TITLE
Operator and Broker updates, initializer chart

### PR DESCRIPTION
**Pull request by umutsahin**
### Broker
* Added broker CRD to broker chart
* Added basic broker resource instance
* Added basic config map for global net 
* Arranged service accounts and RBAC entries based on subctl command

### Operator
* Cleaned up unneeded fields that helm generates
* Arranged service accounts and RBAC entries based on subctl command
* Added cleanup job for helm uninstall, remove submariner first then remove rest

### Initializer
* Added job to initialize cluster
  * Annotate nodes with dns key
  * Annotate first worker as gateway
* Cleanup job for labels and annotations

### CODE REVIEW

**Comment by dfarrell07** [comment]
Wow, thanks for the PR @umutsahin!

**Comment by skitt** [comment]
Thank you for all this work @umutsahin! I’m reviewing this PR but it will take me a few days.

**Comment by dfarrell07** [comment]
@umutsahin CI is catching some issues:

https://github.com/submariner-io/submariner-charts/actions/runs/4764448770/jobs/8561293060?pr=364
https://github.com/submariner-io/submariner-charts/actions/runs/4764448777/jobs/8561291334?pr=364

You can see what passing runs look like here:

https://github.com/submariner-io/submariner-charts/actions/workflows/flake_finder.yml

**Comment by dfarrell07** [comment]
@umutsahin Can you take a look at the failing tests? Thank you again for the PR!

**Comment by dfarrell07** [comment]
(and sorry to be slow to review, I think we all find this large of a PR to be hard to review/intimidating to start)

**Pull request closed without merging**
