### PR TITLE
Fix MCS API CRDs

### PR DESCRIPTION
**Pull request by vthapar**
Update the MCS API CRDs as per definition in
https://github.com/kubernetes-sigs/mcs-api/tree/master/config/crd

Signed-off-by: Vishal Thapar <5137689+vthapar@users.noreply.github.com>

### CODE REVIEW

**Comment by vthapar** [comment]
Mostly a change in indentation. `schema` field needs to be a subfield of `versions` but due to wrong indentation it wasn't. Also adds the subresource->status.

**Review by dfarrell07 — APPROVED** [review]

**Review by skitt — APPROVED** [review]

**Review by aswinsuryan — APPROVED** [review]

**Comment by vthapar** [comment]
Looks like we need to upgrade helm to install the MCS API CRDs correctly. I'll raise a patch to remove them for now and then we can merge this once helm upgrade is ready.

**Comment by dfarrell07** [comment]
Helm v3 update is merged, but we have some conflicting files here now @vthapar.

**Comment by vthapar** [comment]
Not needed with https://github.com/submariner-io/submariner-charts/pull/87 already merged.

**Pull request closed without merging**
