### PR TITLE
Bump to 0.11.2

### PR DESCRIPTION
**Pull request by mkolesnik**
Signed-off-by: Mike Kolesnik <mkolesni@redhat.com>

### CODE REVIEW

**Review by tpantelis — APPROVED** [review]

**Review by dfarrell07 — APPROVED** [review]

**Comment by dfarrell07** [comment]
First impression was that this looks like the inotify error I thought I fixed in https://github.com/submariner-io/shipyard/pull/714.

```
submariner-charts]$ [cluster2] exit 1
[submariner-charts]$ [cluster2] warn_inotify
[submariner-charts]$ [cluster2] warn_inotify
[submariner-charts]$ [cluster2] cat /proc/sys/fs/inotify/max_user_instances
[submariner-charts]$ [cluster2] cat /proc/sys/fs/inotify/max_user_watches
[submariner-charts]$ [cluster2] cat /proc/sys/fs/inotify/max_user_instances
Please increase your inotify settings (currently 56886 and 128):
sudo sysctl fs.inotify.max_user_watches=524288
sudo sysctl fs.inotify.max_user_instances=512
```

But I also see this error, and I know there are infra problems with GitHub at the moment that impact GHAs.

```
[cluster2] ERROR: failed to create cluster: failed to pull image "kindest/node:v1.23": command "docker pull kindest/node:v1.23" failed with error: exit status 1
```

Going back to double-check the PR that I thought fixed this, I can see it working in CI:

```
2022-01-26T15:50:33.6710790Z Download action repository 'actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f' (SHA:5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f)
2022-01-26T15:50:34.2064253Z ##[group]Run sudo sysctl -w fs.inotify.max_user_watches=524288 fs.inotify.max_user_instances=512
2022-01-26T15:50:34.2064854Z [36;1msudo sysctl -w fs.inotify.max_user_watches=524288 fs.inotify.max_user_instances=512[0m
2022-01-26T15:50:34.2115847Z shell: /usr/bin/bash -e {0}
2022-01-26T15:50:34.2116150Z ##[endgroup]
2022-01-26T15:50:34.2767016Z fs.inotify.max_user_watches = 524288
2022-01-26T15:50:34.2767430Z fs.inotify.max_user_instances = 512
```

https://github.com/submariner-io/shipyard/runs/4953887879?check_suite_focus=true

So I'm re-running CI and we'll see what happens.

**Comment by dfarrell07** [comment]
Same error after about a minute of running.

**Review by skitt — APPROVED** [review]

**Comment by dfarrell07** [comment]
Any thoughts about why this is still failing? Or why the new inotify step in the E2E GHA is running in other repos, but not this one?

```
2022-02-03T23:07:59.2544422Z fs.inotify.max_user_watches = 524288
2022-02-03T23:07:59.2545137Z fs.inotify.max_user_instances = 512
```

https://github.com/submariner-io/submariner/pull/1686
https://pipelines.actions.githubusercontent.com/XY3uESDBHEDMVySv1XHhnjBBj2HTkVMErmGSbcdh0GWkFVF5nH/_apis/pipelines/1/runs/18228/signedlogcontent/2?urlExpires=2022-02-04T16%3A26%3A40.2435819Z&urlSigningMethod=HMACV1&urlSignature=Qpy7H2yY0lxtaFKHAvD8xYd%2BTk20z%2FqX%2B50Fwx1JqSA%3D

**Comment by dfarrell07** [comment]
Maybe it's an issue with K8s 1.23? All of those jobs are failing and no others.

**Comment by dfarrell07** [comment]
Ooo, I think it's because this targets the release-0.11 branch and that's causing older shared GHA to run.

```
2022-02-02T07:35:29.7730766Z ##[group]Run submariner-io/shipyard/gh-actions/e2e@release-0.11
2022-02-02T07:35:29.7731068Z with:
2022-02-02T07:35:29.7731265Z   k8s_version: 1.17
2022-02-02T07:35:29.7731469Z   working-directory: .
2022-02-02T07:35:29.7731684Z   target: e2e
2022-02-02T07:35:29.7731862Z   focus: \[.*\]
2022-02-02T07:35:29.7732091Z   skip: \[external-dataplane\]
2022-02-02T07:35:29.7732321Z   testdir: test/e2e
2022-02-02T07:35:29.7732504Z ##[endgroup]
```

https://github.com/submariner-io/submariner-charts/runs/5033230085?check_suite_focus=true

```
      - name: Run E2E deployment and tests
        uses: submariner-io/shipyard/gh-actions/e2e@release-0.11
```

https://github.com/submariner-io/submariner-charts/blob/release-0.11/.github/workflows/e2e.yml#L17

**Comment by dfarrell07** [comment]
This might get it working: https://github.com/submariner-io/shipyard/pull/719

**Comment by mkolesnik** [comment]
WTH 1.23 isn't even in 0.11 why is the CI trying to run it

**Comment by mkolesnik** [comment]
OK so this was merged but is wrong - https://github.com/submariner-io/submariner-charts/pull/199/commits/42e24a428feaf32152faf767d0472a0b0dd0085a

0.11 doesnt know K8s 0.23

**Pull request merged**
