### PR TITLE
Fix iptables/nftables issue

### PR DESCRIPTION
**Pull request by sridhargaddam**
Both iptables and nftables use netfilter framework in the kernel for
packet filtering. Many distributions are moving in the direction of
using nftables over iptables. Although, nftables uses a new command
line utility (named nft), starting from iptables >=1.8, it uses
nftables under the hood while continuing to support the same iptables
syntax from the user.

Quoting from Dan's comment [#]

"In iptables 1.8, the maintainers have "deprecated" the classic ip_tables:
the iptables tool now does userspace translation from the legacy UI/UX,
and uses nf_tables under the hood. So, the commands look and feel the
same, but they're now programming a different kernel subsystem.

The problem arises when you mix and match invocations of iptables 1.6
(the previous stable) and 1.8 on the same machine, because although they
look identical, they're programming different kernel subsystems.

Empirically, this causes weird and wonderful things to happen - things
like if you trace a packet coming from a pod, you see it flowing through
both ip_tables and nf_tables, but even if both accept the packet, it then
vanishes entirely and never gets forwarded"

So, as long as we are programming either nf_tables or iptables, we would
not have any issues. Currently, there is no easy way to identify what type
of rules are programmed on the host. This patch follows the same approach
(as described here [*]) that is taken in OpenShift where the host file
system is mounted inside the docker container and iptables utility on the
host is exec'ed for programming any firewall rules.

[#] https://github.com/kubernetes/kubernetes/issues/71305#issuecomment-448052889
[*] https://github.com/kubernetes/kubernetes/issues/71305#issuecomment-521978797

### CODE REVIEW

**Comment by sridhargaddam** [comment]
JFYI, I verified this change both on ubi-minimal as well as Ubuntu images.

**Comment by mangelajo** [comment]
Looks fine, but this has conflicts to resolve

**Comment by mangelajo** [comment]
Ok, fixed.

**Comment by Oats87** [comment]
@sridhargaddam are there any SCC concerns we have due to this change? I'm pretty sure OCP's `privileged` allows for mounting hostPaths right?

**Comment by sridhargaddam** [comment]
> @sridhargaddam are there any SCC concerns we have due to this change? I'm pretty sure OCP's `privileged` allows for mounting hostPaths right?
AFAICT, yes.

**Comment by sridhargaddam** [comment]
Please note that to have a functional solution, we also need the patch from submariner-io
https://github.com/submariner-io/submariner/pull/135

Both the patches should go together and we also have to host the updated charts in a publicly accessible repo. Currently the charts are hosted at rancher url https://releases.rancher.com/submariner-charts/latest

In KIND based setup, its referenced here https://github.com/submariner-io/submariner/blob/master/scripts/kind-e2e/e2e.sh#L59

CC: @mangelajo , @Oats87 , @skitt, @tpantelis, @dimaunx

**Pull request merged**
