### PR TITLE
Release Helm charts via helm/chart-releaser GHA

### PR DESCRIPTION
**Pull request by dfarrell07**
Use the official Helm chart releasing GitHub Action instead of our
custom bash.

Travis CI can be removed after this commit, as all tests will have
equivalents for GHAs.

Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

### CODE REVIEW

**Comment by dfarrell07** [comment]
I'm not sure how to test this, other than to remove the other releasing logic and see if things still work. :sweat_smile:

**Review by tpantelis — APPROVED** [review]

**Review by mkolesnik — APPROVED** [review]
LGTM

**Review by skitt — APPROVED** [review]

**Comment by skitt** [comment]
@dfarrell07 could you resolve the conflict?

**Comment by dfarrell07** [comment]
Seems like something is wrong with the GH config for this repo. I should be able to merge with @tpantelis and @skitt's approvals but I can't.

**Pull request merged**
